"""initial domain model

Revision ID: 202607140001
Revises:
Create Date: 2026-07-14 10:51:50.577803
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "202607140001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("redaction_policy_version", sa.String(length=128), nullable=False),
        sa.Column("intake_token_hash", sa.String(length=64), nullable=False),
        sa.Column("agent_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_token_hash"),
        sa.UniqueConstraint("intake_token_hash"),
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column("component", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("actual", sa.Text(), nullable=False),
        sa.Column("reproduction", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("service_name", sa.String(length=128), nullable=True),
        sa.Column("service_version", sa.String(length=256), nullable=True),
        sa.Column("correlation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("release", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state IN ('open', 'analyzing', 'resolved')", name="ck_issues_state"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_issues_fingerprint", "issues", ["project_id", "fingerprint"], unique=False)
    op.create_index(op.f("ix_issues_project_id"), "issues", ["project_id"], unique=False)
    op.create_index(
        "ix_issues_project_state_occurred",
        "issues",
        ["project_id", "state", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_issues_summary_trgm",
        "issues",
        ["summary"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"summary": "gin_trgm_ops"},
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("public_id", sa.String(length=128), nullable=False),
        sa.Column("locator", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "public_id", name="uq_repositories_project_public_id"),
    )
    op.create_index(
        op.f("ix_repositories_project_id"), "repositories", ["project_id"], unique=False
    )
    op.create_table(
        "agent_analyses",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("issue_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hypotheses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("status IN ('incomplete', 'complete')", name="ck_agent_analyses_status"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_analyses_issue_id"), "agent_analyses", ["issue_id"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("issue_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("relation", sa.String(length=16), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("redaction_status", sa.String(length=16), nullable=False),
        sa.Column("redaction_policy_version", sa.String(length=128), nullable=False),
        sa.Column("redaction_count", sa.Integer(), nullable=False),
        sa.Column("derived_from", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(observed_at IS NOT NULL AND observed_from IS NULL AND observed_to IS NULL) OR "
            "(observed_at IS NULL AND observed_from IS NOT NULL AND observed_to IS NOT NULL "
            "AND observed_to >= observed_from)",
            name="ck_evidence_observation_time",
        ),
        sa.CheckConstraint("redaction_status = 'sanitized'", name="ck_evidence_redaction_status"),
        sa.CheckConstraint(
            "relation IN ('anchor', 'correlated', 'derived', 'historical')",
            name="ck_evidence_relation",
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_issue_id"), "evidence", ["issue_id"], unique=False)
    op.create_table(
        "issue_repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.String(length=128), nullable=False),
        sa.Column("repository_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("locator", sa.String(length=2048), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("branch", sa.String(length=256), nullable=True),
        sa.Column("subdirectory", sa.String(length=1024), nullable=True),
        sa.CheckConstraint("role IN ('primary', 'related')", name="ck_issue_repositories_role"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "issue_id", "repository_id", name="uq_issue_repositories_issue_public_id"
        ),
    )
    op.create_index(
        op.f("ix_issue_repositories_issue_id"), "issue_repositories", ["issue_id"], unique=False
    )
    op.create_table(
        "resolutions",
        sa.Column("issue_id", sa.String(length=128), nullable=False),
        sa.Column("human_confirmed", sa.Boolean(), nullable=False),
        sa.Column("confirmed_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("analysis_id", sa.String(length=128), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fixes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_in_environment", sa.Boolean(), nullable=False),
        sa.CheckConstraint("human_confirmed", name="ck_resolutions_human_confirmed"),
        sa.ForeignKeyConstraint(["analysis_id"], ["agent_analyses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("issue_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resolutions")
    op.drop_index(op.f("ix_issue_repositories_issue_id"), table_name="issue_repositories")
    op.drop_table("issue_repositories")
    op.drop_index(op.f("ix_evidence_issue_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_agent_analyses_issue_id"), table_name="agent_analyses")
    op.drop_table("agent_analyses")
    op.drop_index(op.f("ix_repositories_project_id"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index("ix_issues_project_state_occurred", table_name="issues")
    op.drop_index(
        "ix_issues_summary_trgm",
        table_name="issues",
        postgresql_using="gin",
        postgresql_ops={"summary": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_issues_project_id"), table_name="issues")
    op.drop_index("ix_issues_fingerprint", table_name="issues")
    op.drop_table("issues")
    op.drop_table("projects")
    # ### end Alembic commands ###
